<a href="https://colab.research.google.com/github/Vishwesh2400/PokeMix_Kaggle/blob/main/PokeMix_Final_To_Execute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('train.csv')

In [ ]:
data

In [ ]:
new_data = data.dropna(axis = 0, how ='any') 

In [ ]:
new_data.shape

In [ ]:
X = new_data.iloc[:,0:42].values

In [ ]:
X

In [ ]:
y = new_data.iloc[:,-2].values
y

array([1, 0, 0, ..., 1, 0, 1])

In [ ]:
y1 = new_data.iloc[:,-1].values
y1

array([20,  6,  1, ...,  2,  3, 10])

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
le = LabelEncoder()
X[:,12] = le.fit_transform(X[:,12])
X[:,10] = le.fit_transform(X[:,10])
X[:,2] = le.fit_transform(X[:,2])
X[:,6] = le.fit_transform(X[:,6])
X[:,4] = le.fit_transform(X[:,4])

X[:,16] = le.fit_transform(X[:,16])
X[:,32] = le.fit_transform(X[:,32])
X[:,17] = le.fit_transform(X[:,17])



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.svm import SVC

In [ ]:
test_data = pd.read_csv('test_new.csv')

In [ ]:
X_t = np.array(test_data)

In [ ]:
le = LabelEncoder()
X_t[:,12] = le.fit_transform(X_t[:,12])
X_t[:,10] = le.fit_transform(X_t[:,10])
X_t[:,2] = le.fit_transform(X_t[:,2])
X_t[:,6] = le.fit_transform(X_t[:,6])
X_t[:,4] = le.fit_transform(X_t[:,4])

X_t[:,16] = le.fit_transform(X_t[:,16])
X_t[:,32] = le.fit_transform(X_t[:,32])
X_t[:,17] = le.fit_transform(X_t[:,17])



In [ ]:
import pickle
SVM_clf = pickle.load(open('Sigmoid.pkl', 'rb'))

In [ ]:
SVM_clf.predict(X_t)
SVM_pro = SVM_clf.predict_proba(X_t)
one_prob = SVM_pro[:,1]
one_prob

array([0.42906313, 0.68604259, 0.11608405, 0.42746861, 0.18246578,
       0.76624801, 0.21649581, 0.4539067 , 0.04531135, 0.11197829,
       0.0957986 , 0.19752316, 0.44218098, 0.506037  , 0.01127332,
       0.26104936, 0.20494748, 0.13197537, 0.25199523, 0.12283821,
       0.06009969, 0.38508087, 0.41508785, 0.44498249, 0.19326255,
       0.27694188, 0.20607038, 0.20421573, 0.05963313, 0.07133409,
       0.64666257, 0.31222147, 0.61935972, 0.08709238, 0.06042997,
       0.33111067, 0.04523381, 0.05299377, 0.07829723, 0.04767825,
       0.03035854, 0.10639668, 0.14562945, 0.01117295, 0.00455489,
       0.08538789, 0.28336234, 0.09791327, 0.06820527, 0.32259609,
       0.04724235, 0.2312979 , 0.05645521, 0.62394607, 0.01478563,
       0.13427486, 0.10282482, 0.04038386, 0.52919102, 0.00768769,
       0.03905563, 0.01247936, 0.19954466, 0.01548441, 0.06875097,
       0.2159721 , 0.10931073, 0.15038248, 0.00916411, 0.19831493,
       0.00913777, 0.28608455, 0.07299527, 0.54863137, 0.17879

In [ ]:
import pickle
SVM_clf1 = pickle.load(open('Linear.pkl', 'rb'))

In [ ]:
a = SVM_clf1.predict(X_t)
p = SVM_clf1.predict_proba(X_t)
p[:,1]

array([0.40327406, 0.69573444, 0.09748719, 0.51873434, 0.13277788,
       0.65174675, 0.10370868, 0.43194882, 0.05101831, 0.11104491,
       0.1164633 , 0.16883355, 0.46121472, 0.43166427, 0.00730753,
       0.20746203, 0.13349859, 0.22452481, 0.20290977, 0.19933273,
       0.0550785 , 0.4362524 , 0.37834666, 0.41806218, 0.20128553,
       0.19267878, 0.30328918, 0.22353699, 0.1066804 , 0.03590449,
       0.3971696 , 0.22698988, 0.54226531, 0.0956486 , 0.07510579,
       0.24375519, 0.12622364, 0.07278603, 0.10892268, 0.05522521,
       0.06856133, 0.10583515, 0.36312839, 0.03886123, 0.03644529,
       0.07962957, 0.17258073, 0.08559369, 0.14723122, 0.43225211,
       0.06977147, 0.33932039, 0.0801776 , 0.71017348, 0.03163635,
       0.13258625, 0.19416392, 0.04756021, 0.54955033, 0.00400672,
       0.05532906, 0.04055914, 0.25483519, 0.04587939, 0.08668156,
       0.17017785, 0.16251987, 0.16318969, 0.03606683, 0.24078153,
       0.01292505, 0.25776964, 0.04200705, 0.5671876 , 0.22515

In [ ]:
one_linear = p[:,1]

In [ ]:
mean_prob = []

In [ ]:
len(one_prob),len(one_linear)

(240, 240)

In [ ]:
for i in range(len(one_prob)):
  mean_prob.append((one_prob[i]+one_linear[i])/2)


In [ ]:
mean_prob

[0.4153744006472588,
 0.6834026537367643,
 0.11078757511457951,
 0.46923489683707587,
 0.16174465770915,
 0.7038068748575055,
 0.16415128439454263,
 0.4413581945694641,
 0.05149681731498103,
 0.11560095779077337,
 0.11024018976935132,
 0.18712302334146577,
 0.4493365436857445,
 0.4672887930240801,
 0.010220177443019111,
 0.23776042894924415,
 0.1733449670934447,
 0.1814957949425931,
 0.2310202047727145,
 0.16470072917503414,
 0.061049571908412176,
 0.4089802295125128,
 0.39658263203918387,
 0.4303294382154818,
 0.20086355269570855,
 0.23850936424917155,
 0.25635990050153135,
 0.21713799904287728,
 0.08722405924215235,
 0.05636779124239763,
 0.52128515400041,
 0.27281112933611845,
 0.5763510412989837,
 0.09535613315388872,
 0.0714883409524261,
 0.29034733714280714,
 0.08985405432132404,
 0.06656981666163936,
 0.09768927584000259,
 0.053579784317157465,
 0.053059797574450084,
 0.11017828533212778,
 0.2546354981178192,
 0.02789417459976317,
 0.02327269429699501,
 0.08630164275485808,
 0.2

In [ ]:
mean_dict = {}

for j in range(X_t.shape[0]):
  mean_dict[X_t[j][0]]={}
for j in range(X_t.shape[0]):
  mean_dict[X_t[j][0]]['Attrition']=mean_prob[j]

In [ ]:
regressor1 = pickle.load(open('RegressorNonScaled.pkl','rb'))

In [ ]:
y__1 = regressor1.predict(X_t)

In [ ]:
np.floor(y__1)

array([ 2.,  3.,  3.,  6.,  3.,  2.,  6.,  4., 14.,  3.,  2.,  4.,  2.,
        0., 13.,  4.,  2.,  3.,  3.,  4., 11.,  8.,  1.,  3.,  0.,  3.,
        8.,  6.,  2.,  4.,  5.,  0.,  0.,  2., 12.,  1., 14.,  4.,  2.,
        6., 15., 13.,  8., 27.,  2.,  0.,  3.,  0.,  0.,  5.,  9.,  9.,
        8.,  2.,  7.,  0., 29., 10.,  5., 21.,  9., 10.,  8.,  3., 20.,
        0., 11., 10., 11.,  2., 15.,  0., 23.,  8.,  4.,  4.,  0., 20.,
        3.,  4.,  7.,  5.,  2., 19., 18.,  2.,  9.,  3., 21., 15., 16.,
        7.,  4.,  2.,  9.,  0.,  4., 24.,  0., 12.,  8.,  8., 12., 10.,
        4.,  2., 28.,  0.,  5., 14.,  8.,  4.,  9., 10., 10.,  8., 13.,
       10.,  3.,  2.,  2.,  0., 15., 20.,  8.,  0.,  5.,  9.,  0.,  4.,
        0.,  2., 10., 11.,  4., 10., 14.,  5., 22.,  2., 10.,  9.,  2.,
        1., 20., 13.,  9.,  3.,  5., 14.,  5.,  5., 19., 10.,  8.,  9.,
        2.,  9.,  5.,  3.,  5.,  0.,  8.,  4.,  5.,  0., 21.,  4.,  0.,
        0.,  6., 10.,  0.,  5., 11.,  0.,  4., 14.,  4., 20., 13

In [ ]:
RFR_clf = pickle.load(open('RegressionScaled.pkl','rb'))

In [ ]:
RFR_pred = RFR_clf.predict(X_t)

In [ ]:
RFR_pred

array([ 2.55813953,  3.95348837,  3.69767442,  6.34883721,  3.88372093,
        1.74418605,  5.97674419,  5.        , 14.97674419,  3.41860465,
        2.34883721,  4.95348837,  2.37209302,  0.72093023, 15.41860465,
        4.48837209,  2.41860465,  3.90697674,  3.81395349,  4.76744186,
       10.55813953,  8.55813953,  1.20930233,  3.53488372,  0.62790698,
        3.69767442,  8.53488372,  6.37209302,  2.58139535,  4.93023256,
        5.44186047,  0.53488372,  0.53488372,  2.41860465, 12.88372093,
        1.41860465, 15.90697674,  4.65116279,  2.72093023,  6.1627907 ,
       15.65116279, 13.27906977,  9.55813953, 27.09302326,  2.55813953,
        0.72093023,  3.81395349,  0.93023256,  0.74418605,  5.39534884,
        9.44186047,  9.30232558,  8.27906977,  2.34883721,  8.65116279,
        0.18604651, 28.81395349, 10.86046512,  5.23255814, 20.76744186,
        9.86046512, 10.06976744,  8.97674419,  4.27906977, 20.74418605,
        0.65116279, 10.93023256, 10.60465116, 12.30232558,  2.37

In [ ]:
y__1,RFR_pred

In [ ]:
mean_years = []

In [ ]:
for i in range(len(RFR_pred)):
  a = (np.floor(y__1[i])+np.floor(RFR_pred[i]))/2
  mean_years.append(np.floor(a))

In [ ]:
for j in range(X_t.shape[0]):
  mean_dict[X_t[j][0]]['Years'] = int(np.floor(mean_years[j]))

In [ ]:
final_test = []


In [ ]:
for i in range(X_t.shape[0]):
  list1 = []
  list1.append(X_t[i][0])
  list1.append(mean_dict[X_t[i][0]]['Attrition'])
  list1.append(mean_dict[X_t[i][0]]['Years'])
  final_test.append(list1)

In [ ]:
final = pd.DataFrame(final_test,columns = ('ID','Attrition','YearsAtCompany'))
final

ID  Attrition  YearsAtCompany
0      1   0.408750               2
1      2   0.670314               3
2      3   0.113384               3
3      4   0.462669               6
4      5   0.163084               3
..   ...        ...             ...
235  236   0.339778               0
236  237   0.110940               4
237  238   0.058977               0
238  239   0.180985               3
239  240   0.557257               2

[240 rows x 3 columns]

In [ ]:
print(final

      ID  Attrition  YearsAtCompany
0      1   0.408750               2
1      2   0.670314               3
2      3   0.113384               3
3      4   0.462669               6
4      5   0.163084               3
..   ...        ...             ...
235  236   0.339778               0
236  237   0.110940               4
237  238   0.058977               0
238  239   0.180985               3
239  240   0.557257               2

[240 rows x 3 columns]


In [ ]:
final.to_csv('day2_13.csv')